[tools]
chezmoi = "latest"

# node
node= "latest"
npm = "latest"
pnpm = "latest"
"npm:@antfu/ni" = "latest"
"npm:taze" = "latest"

# python
python = "latest"
uv = "latest"

usage = "latest"
atuin = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["pnpm", "node"]
minimum_release_age = "0"
