[tools]
chezmoi = "latest"
npm = "latest"
pnpm = "latest"
python = "latest"
uv = "latest"
usage = "latest"
node= { version = "24.19.0", postinstall = """
npm install -g --ignore-scripts @earendil-works/pi-coding-agent @antfu/ni @github/copilot
""" }

[settings]
idiomatic_version_file_enable_tools = ["node"]
